### ISSUE TITLE
B2.6	Unique Forgot Password Link

### ISSUE THREAD

**Issue by GuyWhoCode** [LetsMesh/Site#113]
Story: **As a User (Mentor, Mentee, or Educator), I want to be able to request a password change if I forgot my password.**

Details: Generate a unique link for each user to reset their password. Perhaps implemented with JWTs? Requires working with the person assigned to #110  to connect the two tasks together.

Technical Details:
- Django
- JWT
- Full-Stack

**Comment by misslame** [comment]
This was addressed in #110
