### ISSUE TITLE
F1.2 Enable/Disable Dark Mode

### ISSUE THREAD

**Issue by Leaversa** [LetsMesh/Site#119]
Story: As a night owl account owner mentor, mentee, or educator, I want to be able to switch to a dark theme version of the site so I can look at it better.

Details: After a user enables/disables dark theme, set the display theme in the user's account table to match the current theme and update the current page accordingly.

Technical Details:

- Full-Stack
- React
- UI/UX
- MySQL
- MUI
- Django

**Comment by blu3eee** [comment]
this was resolved by PR #353
