### ISSUE TITLE
G1.1 Init Accounts Table

### ISSUE THREAD

**Issue by rezatnoMsirhC** [LetsMesh/Site#125]
Write a SQL query to define the schema of and create the Accounts table.

This is the current schema:
- accountID (primary key)
- email
- encryptedPass
- phoneNum
- displayTheme
- connectedAccounts
- enable2Factor
- isMentor
- isMentee

Refer to [the UML-Database diagrams.net Page](https://app.diagrams.net/#G18i2FGzLBHPOk-yKIdq-dVpT0CnBap6Ri) for the latest details.

**Comment by misslame** [comment]
peppa
