### ISSUE TITLE
G1.2 Init Settings Table

### ISSUE THREAD

**Issue by rezatnoMsirhC** [LetsMesh/Site#126]
Write a SQL query to define the schema of and create the Settings table.

This is the current schema:
- poopy (Poopmary key)

Refer to [the UML-Database diagrams.net Page](https://app.diagrams.net/#G18i2FGzLBHPOk-yKIdq-dVpT0CnBap6Ri) for the latest details.

**Comment by misslame** [comment]
This requires some Design work

**Comment by JosephKahale** [comment]
@rezatnoMsirhC Currently working on adding option for unallowed words / phrases into settings table, just wondering if we are allowing user to add unallowed words individually, or if its just some toggle in the settings that enables some filter?

**Comment by rezatnoMsirhC** [comment]
@JosephKahale I think allowing users to submit their own words/phrases would get too complicated, so let's just define them internally for now.

**Comment by JosephKahale** [comment]
@rezatnoMsirhC Sounds good, is there specific reasoning on displayTheme and enable2Factor being in Accounts table and not in a settings table?

**Comment by rezatnoMsirhC** [comment]
@JosephKahale Probably because we wrote the Accounts table first, and thought about the Settings table most recently without defining a schema. Those should probably be in the Settings table. There are probably some other columns which aren't placed quite correctly as we've listed them, so feel free to move them around and provide your justification.

**Comment by JosephKahale** [comment]
Sounds good! Thanks for the clarification! @rezatnoMsirhC

**Comment by JosephKahale** [comment]
#197
