### ISSUE TITLE
F3.1 Logged In Home Screen

### ISSUE THREAD

**Issue by misslame** [LetsMesh/Site#134]
Story: **As a product owner, I want to be able to ensure a safe and welcoming environment on the site/app by restricting language to only include appropriate language.**

Details: Follow the figma design of the home screen that is logged in. Create any issues for gaps in functionality and describe their requirements properly following task format.

Technical Details:
- Front-end
- React 
- MUI
- UI/UX

**Comment by rllov** [comment]
https://github.com/LetsMesh/Site/tree/leaf/F3.1-Logged_In_Home_Screen
