### ISSUE TITLE
A4.1 Select Suggested Tags

### ISSUE THREAD

**Issue by misslame** [LetsMesh/Site#14]
﻿﻿Story: ﻿﻿﻿As a User (Mentor, Mentee, or Educator), I want to be able to select tags from a catalog to include on my profile that indicates my professional and casual interests.﻿
﻿
﻿﻿Details: ﻿
﻿When the user is editing profile tags & interests, suggest some default tags to apply and allow users to select and add them.
﻿
﻿﻿Technical Information:
- ﻿﻿React
- May require HTTP API call library (Axios)
- Fetch Suggested Tags (isDefault) GET reques
- POST Api ﻿Call
- Display Suggested Tags
- Full-stack

**Comment by jaayzee** [comment]
Implemented covered in issue #309
