### ISSUE TITLE
A4.2 Delete Profile Tags

### ISSUE THREAD

**Issue by misslame** [LetsMesh/Site#15]
﻿﻿Story: ﻿﻿﻿As a User (Mentor, Mentee, or Educator), I want to be able to select tags from a catalog to include on my profile that indicates my professional and casual interests.﻿
﻿
﻿﻿Details: ﻿
﻿When the user is editing profile tags, allow the deletion of some tags.
﻿
﻿﻿Technical Information:
- ﻿﻿React
- May require HTTP API call library (Axios)
- POST Api Call
- Show tags deleted.
- Full-stack

**Comment by tdang2180** [comment]
Covered in #18
