### ISSUE TITLE
Add user token field to Settings table

### ISSUE THREAD

**Issue by JRSiwiecki** [LetsMesh/Site#218]
For issue [#74](https://github.com/LetsMesh/Site/issues/74), one current plan for email confirmation is to store a generated user token in the settings table for the user, and when an email is sent to them, we check that the token in the url is the same one stored in the settings table, so that other users can't verify someone's email for them in a sense. 

If implemented, this would require a change in issue [#126](https://github.com/LetsMesh/Site/issues/126) where the settings table is initialized, and likely also an update for the database UML.

Related pull requests: PR [#237](https://github.com/LetsMesh/Site/pull/237), PR [#197](https://github.com/LetsMesh/Site/pull/197)

**Comment by JRSiwiecki** [comment]
For clarification, the token is a hex-string of 32 characters.

**Comment by JosephKahale** [comment]
@JRSiwiecki Just wanted to make sure this is still the plan, so I can change the UML as well as the settings table.

**Comment by JRSiwiecki** [comment]
@JosephKahale Yes this is still the idea I'd like to work with, thanks!

**Comment by JosephKahale** [comment]
@JRSiwiecki Would you still use the isVerified bool in the settings table? Or is it not needed anymore due to the 32 char token?

**Comment by JRSiwiecki** [comment]
@JosephKahale I figure that it would still be necessary so as to not send repeat confirmation emails once a user is already verified, but if you'd like to remove the field entirely then I suppose something could be done where if the user's token field isn't null, then in theory we wouldn't need isVerified, but I feel as though it would be simpler to just keep the isVerified field.

**Comment by JRSiwiecki** [comment]
Closed with [#245 ](https://github.com/LetsMesh/Site/pull/245/files)
