### ISSUE TITLE
BUG: Add Dates to Education Table

### ISSUE THREAD

**Issue by misslame** [LetsMesh/Site#282]
Include optional  start & end date for the individual education within the database schema. 

Notes: 
- MySQL
- Django
- Python 
- Back-End

**Comment by JRSiwiecki** [comment]
Note: The start and end dates would be present on the EducationBrdige table, and it also appears that the accountID and educationID would both need to be changed from OneToOne field to ForeignKey to properly implement the UML design, as the current OneToOne field only allows for 1 account to have 1 EducationBridge, which means an account can only ever display 1 education, which is incorrect.

P.S.: The optionalDescription should also be moved from Education to EducationBridge.
