### ISSUE TITLE
BUG: Add Dates to Occupation 

### ISSUE THREAD

**Issue by misslame** [LetsMesh/Site#283]
Include optional start & end date for the individual occupation within the database schema.

Notes:
MySQL
Django
Python
Back-End

**Comment by JRSiwiecki** [comment]
Note: The start and end dates would be present on the OccupationBridge table, and it also appears that the accountID and occupationID would both need to be changed from OneToOne field to ForeignKey to properly implement the UML design, as the current OneToOne field only allows for 1 account to have 1 OccupationBridge, which means an account can only ever display 1 occupation, which is incorrect.
