### ISSUE TITLE
BUG: Adapt Profile Page To Use Theming

### ISSUE THREAD

**Issue by Darren52BT** [LetsMesh/Site#289]
Adapt the Profile Page to use the MUI theme defined in the theme folder.

**Comment by misslame** [comment]
@Darren52BT Are you working on this?

**Comment by Darren52BT** [comment]
> @Darren52BT Are you working on this?

No but I can take it on too, shouldn't be a problem.

Edit: oh I see I was working on this before, but yeah I'll start working on this again.
