### ISSUE TITLE
B1.1 UI/UX Display for sign up

### ISSUE THREAD

**Issue by misslame** [LetsMesh/Site#64]
Story: **As a User (Mentor, Mentee, or Educator), I want to be able to create an account and sign up with my email**

Details: User Interface including all the functionality such as password protection on the display, clicking buttons, info tooltips, etc.  (Follow the Figma Design) 

Technical Details:
- Front-end
- React
- HTML/CSS
- UI/UX

**Comment by misslame** [comment]
@jamsge Please Work on Sign UP Step 1
@ethan-ngo  Please work on Sign Up Step 2
@Shadowowl888  Please work on Sign UP Step 3

**Comment by jamsge** [comment]
https://github.com/LetsMesh/Site/tree/leaf/B1.1-UIForSignUp

@ethan-ngo @Shadowowl888
