### ISSUE TITLE
A6.1 Input/Change Occupation

### ISSUE THREAD

**Issue by rezatnoMsirhC** [LetsMesh/Site#65]
As a User (Mentor, Mentee, or Educator), I want to be able to input and change my occupation.

Details: Follow figma design to build forms, tool tips, and any input boxes for occupation entry

Technical Details:
- Front-end
- React
- HTML
- CSS
- UI
- UX

**Comment by misslame** [comment]
Please work with @PattyCakesxD who is doing the profile base
